#!/bin/bash
echo "Crossbuilder v0.0.4"
if [[ $1 == '' ]]
then
	exit
fi
if [[ $1 == '-s' ]] || [[ $1 == '--setup' ]]
then
	wine cmd /c pip install -r requirements.txt >/dev/null 2>&1
	wineserver -k
	exit
elif [[ $2 == '-r' ]] || [[ $2 == '--remove' ]]
then
	echo "Removing..."
	rm ~/.local/bin/$(echo $1 | sed 's/\.[^.]*$//')
	exit
elif [[ $2 == '-bi' ]] || [[ $2 == '--binary-install' ]]
then
	echo "Installing without compiling..."
	mv $1 ~/.local/bin/
	chmod +x ~/.local/bin/$1
	exit
fi

echo "Building for GNU/Linux..."
set -x
pip3 install -r requirements.txt >/dev/null 2>&1
pip3 install pyinstaller >/dev/null 2>&1
pyinstaller --onefile $1 >/dev/null 2>&1
rm -rf build
rm -rf __pycache__
rm -f *.spec

set +x > /dev/null 2>&1
echo "Building for windows under wine..."
set -x
wine pyinstaller --onefile $1 >/dev/null 2>&1
wineserver -k
rm -rf build
rm -rf __pycache__
rm -f *.spec

set +x > /dev/null 2>&1
if [[ $2 == '-i' ]] || [[ $2 == '--install' ]]
then
	echo "Installing..."
	mv dist/$(echo $1 | sed 's/\.[^.]*$//') ~/.local/bin/
	chmod +x ~/.local/bin/$(echo $1 | sed 's/\.[^.]*$//')
fi
